global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld_exporter:9104']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
